DROP TYPE MOVIES_T FORCE;
DROP TYPE COPIES_T FORCE;
DROP TYPE PRODUCTION_COMPAGNIES_T;
DROP TYPE COMPAGNIES_T;
DROP TYPE CERTIFICATIONS_T;
DROP TYPE COUNTRIES_T;
DROP TYPE MOVIE_PLAY_T;
DROP TYPE MOVIE_DIRECT_T;
DROP TYPE LOGS_T;
DROP TYPE LANGUAGES_T;
DROP TYPE SPOKEN_LANGUAGES_T;
DROP TYPE MOVIE_GENRES_T;
DROP TYPE GENRES_T;

CREATE OR REPLACE TYPE MOVIES_T AS OBJECT (
	id INTEGER,
	title VARCHAR2(100),
	overview VARCHAR2(1000),
	release_date DATE,
	vote_average INTEGER,
	vote_count INTEGER,
	certification INTEGER,
	production_country VARCHAR2(2),
	runtime INTEGER,
	nb_copies INTEGER
};
/

CREATE OR REPLACE TYPE COPIES_T AS OBJECT (
	num_copy INTEGER,
	movie INTEGER       
};
/

CREATE OR REPLACE TYPE PRODUCTION_COMPAGNIES_T AS OBJECT (
	company INTEGER,
	movie INTEGER
};
/

CREATE OR REPLACE TYPE ARR_PRODUCTION_COMPAGNIES_T IS TABLE OF PRODUCTION_COMPAGNIES_T;
/

CREATE OR REPLACE TYPE COMPAGNIES_T AS OBJECT (
	id INTEGER,
	name VARCHAR2(70)
};
/

CREATE OR REPLACE TYPE CERTIFICATIONS_T AS OBJECT (
	id INTEGER,
	name VARCHAR2(5),
	description VARCHAR2(250)
};
/

CREATE OR REPLACE TYPE IMAGES_T AS OBJECT (
	id INTEGER,
	image BLOB,
	movie INTEGER       
};
/

CREATE OR REPLACE TYPE COUNTRIES_T AS OBJECT (
	code CHAR(2),
	name VARCHAR2(40)
};
/

CREATE OR REPLACE TYPE MOVIE_PLAY_T AS OBJECT (
	movie INTEGER,
	artist INTEGER,     
};
/

CREATE OR REPLACE TYPE ARTISTS_T AS OBJECT (
	id INTEGER,
	name VARCHAR2(50)
};
/

CREATE OR REPLACE TYPE ARR_ARTISTS_T IS TABLE OF ARTISTS_T;
/ 

CREATE OR REPLACE TYPE MOVIE_DIRECT_T AS OBJECT (
	movie INTEGER,
	director INTEGER
};
/

CREATE OR REPLACE TYPE ARR_MOVIE_DIRECT_T IS TABLE OF MOVIE_DIRECT_T;
/
CREATE OR REPLACE TYPE LOGS_T AS OBJECT (
	id INTEGER,
	when_ DATE,
	error_code INTEGER,
	what_ VARCHAR2(4000),
	where_ VARCHAR2(255)
};
/

CREATE OR REPLACE TYPE ARR_LOGS_T IS TABLE OF LOGS_T;
/

CREATE OR REPLACE TYPE LANGUAGES_T AS OBJECT (
	code CHAR(2),
	name VARCHAR2(20)   
};
/

CREATE OR REPLACE TYPE SPOKEN_LANG_T AS OBJECT (
	language CHAR(2),
	movie INTEGER
};
/

CREATE OR REPLACE TYPE ARR_SPOKEN_LANG_T IS TABLE OF SPOKEN_LANG_T;
/

CREATE OR REPLACE TYPE MOVIE_GENRES_T AS OBJECT (
	genre INTEGER,
	movie INTEGER       
};
/

CREATE OR REPLACE TYPE GENRES_T AS OBJECT (
	id INTEGER,
	name VARCHAR2(16)
};
/