DROP SEQUENCE SEQUENCE_IMAGE;
DROP SEQUENCE SEQUENCE_CERTIF;
DROP SEQUENCE SEQUENCE_ERROR;

CREATE SEQUENCE SEQUENCE_IMAGE START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQUENCE_CERTIF START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQUENCE_ERROR START WITH 1 INCREMENT BY 1;