/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Thibault
 */
public class PlacesCC1 extends javax.swing.JFrame
{

    /**
     * Creates new form PlacesCC1
     */
    public PlacesCC1()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bgDate = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pSelectionJour = new javax.swing.JPanel();
        rbToday = new javax.swing.JRadioButton();
        rbOther = new javax.swing.JRadioButton();
        dcDate = new com.toedter.calendar.JDateChooser();
        bRecherche = new javax.swing.JButton();
        pProgrammation = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProg = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Places CC1");

        pSelectionJour.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sélection du jour de projection", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bgDate.add(rbToday);
        rbToday.setText("Aujourd'hui");
        rbToday.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbTodayActionPerformed(evt);
            }
        });

        bgDate.add(rbOther);
        rbOther.setText("Autre date");
        rbOther.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbOtherActionPerformed(evt);
            }
        });

        dcDate.setEnabled(false);

        bRecherche.setText("Recherche");
        bRecherche.setEnabled(false);
        bRecherche.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bRechercheActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pSelectionJourLayout = new javax.swing.GroupLayout(pSelectionJour);
        pSelectionJour.setLayout(pSelectionJourLayout);
        pSelectionJourLayout.setHorizontalGroup(
            pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSelectionJourLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbToday)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 370, Short.MAX_VALUE)
                .addComponent(bRecherche)
                .addGap(197, 197, 197)
                .addComponent(rbOther)
                .addGap(18, 18, 18)
                .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pSelectionJourLayout.setVerticalGroup(
            pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSelectionJourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbToday)
                        .addComponent(rbOther)
                        .addComponent(bRecherche)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pProgrammation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        pProgrammation.setEnabled(false);

        tProg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String []
            {
                "Date", "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        tProg.setEnabled(false);
        jScrollPane1.setViewportView(tProg);

        javax.swing.GroupLayout pProgrammationLayout = new javax.swing.GroupLayout(pProgrammation);
        pProgrammation.setLayout(pProgrammationLayout);
        pProgrammationLayout.setHorizontalGroup(
            pProgrammationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        pProgrammationLayout.setVerticalGroup(
            pProgrammationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenu3.setText("Connexion");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Connexion Oracle");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem1);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pProgrammation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pSelectionJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSelectionJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pProgrammation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOtherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rbOtherActionPerformed
    {//GEN-HEADEREND:event_rbOtherActionPerformed
        if(this.rbOther.isSelected())
            this.dcDate.setEnabled(true);
    }//GEN-LAST:event_rbOtherActionPerformed

    private void rbTodayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rbTodayActionPerformed
    {//GEN-HEADEREND:event_rbTodayActionPerformed
        this.dcDate.setEnabled(false);
    }//GEN-LAST:event_rbTodayActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        // Connexion à Oracle (CC1)
        
        // Enable panel + jTable + bouton
        this.pProgrammation.setEnabled(true);
        this.tProg.setEnabled(true);
        this.bRecherche.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void bRechercheActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bRechercheActionPerformed
    {//GEN-HEADEREND:event_bRechercheActionPerformed
        
    }//GEN-LAST:event_bRechercheActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PlacesCC1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bRecherche;
    private javax.swing.ButtonGroup bgDate;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pProgrammation;
    private javax.swing.JPanel pSelectionJour;
    private javax.swing.JRadioButton rbOther;
    private javax.swing.JRadioButton rbToday;
    private javax.swing.JTable tProg;
    // End of variables declaration//GEN-END:variables
}
