/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package GUI;

import java.awt.Color;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import utils.oracle.RechCC1;

/**
 *
 * @author Thibault
 */
public class PlacesCC1 extends javax.swing.JFrame
{
    
    private ArrayList<JTable> tabs;
    
    public PlacesCC1()
    {
        initComponents();
        
        this.Status.setBackground(Color.green);
        tabs = new ArrayList<>();
        tabs.add(tProg);
        tabs.add(tProg1);
        tabs.add(tProg2);
        tabs.add(tProg3);
        tabs.add(tProg4);
        tabs.add(tProg5);
        tabs.add(tProg6);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        bgDate = new javax.swing.ButtonGroup();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        pSelectionJour = new javax.swing.JPanel();
        rbToday = new javax.swing.JRadioButton();
        rbOther = new javax.swing.JRadioButton();
        dcDate = new com.toedter.calendar.JDateChooser();
        bRecherche = new javax.swing.JButton();
        Status = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        pProgrammation = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tProg = new javax.swing.JTable();
        pProgrammation1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tProg1 = new javax.swing.JTable();
        pProgrammation2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tProg2 = new javax.swing.JTable();
        pProgrammation3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tProg3 = new javax.swing.JTable();
        pProgrammation4 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tProg4 = new javax.swing.JTable();
        pProgrammation5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tProg5 = new javax.swing.JTable();
        pProgrammation6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tProg6 = new javax.swing.JTable();
        jMenuBar2 = new javax.swing.JMenuBar();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Places CC1");

        pSelectionJour.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sélection du jour de projection", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        bgDate.add(rbToday);
        rbToday.setSelected(true);
        rbToday.setText("Aujourd'hui");
        rbToday.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbTodayActionPerformed(evt);
            }
        });

        bgDate.add(rbOther);
        rbOther.setText("Autre date");
        rbOther.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rbOtherActionPerformed(evt);
            }
        });

        dcDate.setEnabled(false);

        bRecherche.setText("Recherche");
        bRecherche.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                bRechercheActionPerformed(evt);
            }
        });

        Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Status.setText("Status");

        javax.swing.GroupLayout pSelectionJourLayout = new javax.swing.GroupLayout(pSelectionJour);
        pSelectionJour.setLayout(pSelectionJourLayout);
        pSelectionJourLayout.setHorizontalGroup(
            pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pSelectionJourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pSelectionJourLayout.createSequentialGroup()
                        .addComponent(rbToday)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bRecherche)
                        .addGap(194, 194, 194)
                        .addComponent(rbOther)
                        .addGap(18, 18, 18)
                        .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pSelectionJourLayout.setVerticalGroup(
            pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSelectionJourLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dcDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pSelectionJourLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbToday)
                        .addComponent(rbOther)
                        .addComponent(bRecherche)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Status, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );

        pProgrammation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tProg);

        javax.swing.GroupLayout pProgrammationLayout = new javax.swing.GroupLayout(pProgrammation);
        pProgrammation.setLayout(pProgrammationLayout);
        pProgrammationLayout.setHorizontalGroup(
            pProgrammationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        pProgrammationLayout.setVerticalGroup(
            pProgrammationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("   J  ", pProgrammation);

        pProgrammation1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProg1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tProg1);

        javax.swing.GroupLayout pProgrammation1Layout = new javax.swing.GroupLayout(pProgrammation1);
        pProgrammation1.setLayout(pProgrammation1Layout);
        pProgrammation1Layout.setHorizontalGroup(
            pProgrammation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        pProgrammation1Layout.setVerticalGroup(
            pProgrammation1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("J+1", pProgrammation1);

        pProgrammation2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProg2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tProg2);

        javax.swing.GroupLayout pProgrammation2Layout = new javax.swing.GroupLayout(pProgrammation2);
        pProgrammation2.setLayout(pProgrammation2Layout);
        pProgrammation2Layout.setHorizontalGroup(
            pProgrammation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        pProgrammation2Layout.setVerticalGroup(
            pProgrammation2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("J+2", pProgrammation2);

        pProgrammation3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProg3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tProg3);

        javax.swing.GroupLayout pProgrammation3Layout = new javax.swing.GroupLayout(pProgrammation3);
        pProgrammation3.setLayout(pProgrammation3Layout);
        pProgrammation3Layout.setHorizontalGroup(
            pProgrammation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        pProgrammation3Layout.setVerticalGroup(
            pProgrammation3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("J+3", pProgrammation3);

        pProgrammation4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProg4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tProg4);

        javax.swing.GroupLayout pProgrammation4Layout = new javax.swing.GroupLayout(pProgrammation4);
        pProgrammation4.setLayout(pProgrammation4Layout);
        pProgrammation4Layout.setHorizontalGroup(
            pProgrammation4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        pProgrammation4Layout.setVerticalGroup(
            pProgrammation4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("J+4", pProgrammation4);

        pProgrammation5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProg5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tProg5);

        javax.swing.GroupLayout pProgrammation5Layout = new javax.swing.GroupLayout(pProgrammation5);
        pProgrammation5.setLayout(pProgrammation5Layout);
        pProgrammation5Layout.setHorizontalGroup(
            pProgrammation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        pProgrammation5Layout.setVerticalGroup(
            pProgrammation5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("J+5", pProgrammation5);

        pProgrammation6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Programmation", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        tProg6.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String []
            {
                "Titre", "Réalisateurs", "Public", "Durée", "Séance", "Salle", "Places restantes"
            }
        )
        {
            Class[] types = new Class []
            {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex)
            {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(tProg6);

        javax.swing.GroupLayout pProgrammation6Layout = new javax.swing.GroupLayout(pProgrammation6);
        pProgrammation6.setLayout(pProgrammation6Layout);
        pProgrammation6Layout.setHorizontalGroup(
            pProgrammation6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1076, Short.MAX_VALUE)
                .addContainerGap())
        );
        pProgrammation6Layout.setVerticalGroup(
            pProgrammation6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pProgrammation6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("J+6", pProgrammation6);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSelectionJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pSelectionJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbOtherActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rbOtherActionPerformed
    {//GEN-HEADEREND:event_rbOtherActionPerformed
        if(this.rbOther.isSelected())
            this.dcDate.setEnabled(true);
    }//GEN-LAST:event_rbOtherActionPerformed

    private void rbTodayActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rbTodayActionPerformed
    {//GEN-HEADEREND:event_rbTodayActionPerformed
        this.dcDate.setEnabled(false);
    }//GEN-LAST:event_rbTodayActionPerformed

    private void bRechercheActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_bRechercheActionPerformed
    {//GEN-HEADEREND:event_bRechercheActionPerformed
        try
        {
            Calendar date;
            if(this.rbToday.isSelected())
                date = Calendar.getInstance();
            else
                date = this.dcDate.getCalendar();            
            
            RechCC1.Recherche(this, date);            
        }
        catch (IOException ex)
        {
            Logger.getLogger(PlacesCC1.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }//GEN-LAST:event_bRechercheActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(PlacesCC1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new PlacesCC1().setVisible(true);
            }
        });
    }

    public ArrayList<JTable> getTabs()
    {
        return tabs;
    }

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Status;
    private javax.swing.JButton bRecherche;
    private javax.swing.ButtonGroup bgDate;
    private com.toedter.calendar.JDateChooser dcDate;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pProgrammation;
    private javax.swing.JPanel pProgrammation1;
    private javax.swing.JPanel pProgrammation2;
    private javax.swing.JPanel pProgrammation3;
    private javax.swing.JPanel pProgrammation4;
    private javax.swing.JPanel pProgrammation5;
    private javax.swing.JPanel pProgrammation6;
    private javax.swing.JPanel pSelectionJour;
    private javax.swing.JRadioButton rbOther;
    private javax.swing.JRadioButton rbToday;
    private javax.swing.JTable tProg;
    private javax.swing.JTable tProg1;
    private javax.swing.JTable tProg2;
    private javax.swing.JTable tProg3;
    private javax.swing.JTable tProg4;
    private javax.swing.JTable tProg5;
    private javax.swing.JTable tProg6;
    // End of variables declaration//GEN-END:variables
}
